import { useRouter } from 'next/router'
import React from 'react'
import Restaurant from '../../../shared/components/client/restaurants/Restaurant'
import Head from 'next/head'
import ClientLayout from '../../../shared/components/layout/client/Header'

const index = () => {
  const router = useRouter()
  const restaurantId = router.query.id
  return (
    <>
      <Head>
        <title>Foody | Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>

      <ClientLayout>
        <Restaurant restaurantId={restaurantId} />
      </ClientLayout>
    </>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  };
}

export default index
