import Head from 'next/head'
import AdminAside from '../../admin/adminAside'
import Navbar from '../../admin/Navbar'

const AdminLayout = ({ children }) => {
  return (
    <div className="bg-darkBlue_1 min-h-screen px-4">
      <Head>
        <title>Foody | Adminn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>
      <Navbar adminNavbar={true} />
      <AdminAside />
      <div className="pt-[100px] ps-[240px]">{children}</div>
    </div>
  )
}
export default AdminLayout
