import Head from 'next/head'
import AdminAside from '../../admin/adminAside'
import Navbar from '../../admin/Navbar'

const AdminLayout = ({ children }) => {
  return (
<<<<<<< HEAD
    <div className="bg-darkBlue_1 min-h-screen px-4">
      <Head>
        <title>Foody | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>
=======
    <div className="bg-[#1E1E30] min-h-screen px-4">
>>>>>>> b07e4d6a05c4394fcc27e3fdb7f1e3e8cc2b1ddb
      <Navbar adminNavbar={true} />
      <AdminAside />
      <div className="pt-[100px] ps-[240px]">{children}</div>
    </div>
  )
}
export default AdminLayout
