import { useTranslation } from 'react-i18next'
import UserAside from '../../shared/components/client/userAside'
import Head from 'next/head'
import ClientLayout from '../../shared/components/layout/client/Header'

const UserCheckout = () => {
  const { t } = useTranslation()
  return (
    <>
      <Head>
        <title>Foody | User Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>
      <ClientLayout>
        <section className="m-4 flex justify-center gap-10">
          <UserAside />
          <div className="w-full flex  flex-col flex-wrap gap-x-1 gap-y-8 bg-white sm:bg-whiteLight1">
            <h1>User Checkout</h1>
          </div>
        </section>
      </ClientLayout>
    </>
  )
}
export default UserCheckout
