import Head from 'next/head'
import UserAside from '../../shared/components/client/userAside'
import ClientLayout from '../../shared/components/layout/client/Header'
import { useTranslation } from 'react-i18next'
import { useEffect, useState } from 'react'
import { getProductForBasket } from '../../shared/services/axios'
import UserBasketDetail from '../../shared/components/client/userBasketDetail'
import { useGlobalStore } from '../../shared/services/provider'

const UserBasket = () => {
  const { t } = useTranslation()
  const { basketData, setBasketData } = useGlobalStore()
  const renderBasketProducts = async () => {
    const res = await getProductForBasket()
    setBasketData(res?.data.result.data)
  }

  useEffect(() => {
    renderBasketProducts()
  }, [])

  return (
    <>
      <Head>
        <title>Foody | User Basket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>
      <ClientLayout>
        <section className="m-4 flex justify-center gap-10">
          <UserAside />
          <div className="w-full flex  flex-col flex-wrap gap-x-1 gap-y-8 bg-white sm:bg-whiteLight1">
            <UserBasketDetail
              data={basketData}
              itemsCount={basketData?.total_item}
            />
          </div>
        </section>
      </ClientLayout>
    </>
  )
}
export default UserBasket
