import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

const AdminDashboard = () => {
  const router = useRouter()

  useEffect(() => {
    router.push('/admin/dashboard')
  }, [])

  return (
    <>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/admin-icon.png" />
      </Head>
    </>
  )
}

export default AdminDashboard
