// import Head from 'next/head'
// import { useRouter } from 'next/router'
// import { useEffect } from 'react'

// const AdminDashboard = () => {
//   const router = useRouter()
//   useEffect(() => {
//     const localAdmin = localStorage.getItem('localAdmin')
//     if (!localAdmin) {
//       router.push('/admin/login')
//     } else {
//       router.push('/admin/dashboard')
//     }
//   }, [router])

//   return (
//     <>
//       <Head>
//         <title>Admin</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/admin-icon.png" />
//       </Head>
//     </>
//   )
// }

// export default AdminDashboard
