import Head from 'next/head'
import AuthCheck from '../../shared/components/admin/authCheck'

const AdminDashboard = () => {
  return (
    <>
      <AuthCheck>
        <Head>
          <title>Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/admin-icon.png" />
        </Head>
      </AuthCheck>
    </>
  )
}

export default AdminDashboard
