import Head from 'next/head'
import ClientLayout from '../../shared/components/layout/client/Header'

const Restaurants = () => {
  return (
    <>
      <Head>
        <title>Foody | Restaurants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>

      <ClientLayout>
        <div>Restaurants page</div>
      </ClientLayout>
    </>
  )
}
export default Restaurants
