import Head from 'next/head'
import ClientLayout from '../../shared/components/layout/client/Header'
import { useTranslation } from 'react-i18next'
import Image from 'next/image'
import { useState } from 'react'
const Faqs = () => {
  const { t } = useTranslation()
  const [isContentVisible, setContentVisibility] = useState([
    false,
    false,
    false,
    false,
    false,
  ])
  const toggleContent = (index) => {
    const newVisibleContents = [...isContentVisible]
    newVisibleContents[index] = !newVisibleContents[index]
    setContentVisibility(newVisibleContents)
  }
  return (
    <>
      <Head>
        <title>Foody | Faqs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>
      <ClientLayout>
        <main className=" flex flex-col items-center gap-5 mb-8">
          <p data-aos="zoom-in" className=" text-5xl font-medium pb-5">
            F.A.Q
          </p>
          {[
            { key: 'faqDesc', content: 'faqDesc6' },
            { key: 'faqDesc2', content: 'faqDesc6' },
            { key: 'faqDesc3', content: 'faqDesc6' },
            { key: 'faqDesc4', content: 'faqDesc6' },
            { key: 'faqDesc5', content: 'faqDesc6' },
          ].map((faq, index) => (
            <div
              key={faq.key}
              className=" p-6 w-3/4 mx-auto bg-white shadow-md"
            >
              <div className="flex justify-between mb-3">
                <p className=" text-2xl font-medium">{t(faq.key)}</p>
                <button onClick={() => toggleContent(index)}>
                  <Image
                    width={25}
                    height={0}
                    src={isContentVisible[index] ? 'plus.svg' : 'minus.svg'}
                    alt={isContentVisible[index] ? 'plus' : 'minus'}
                  />
                </button>
              </div>
              {isContentVisible[index] && (
                <div className="text-grayText1 text-lg leading-7 font-medium">
                  {t(faq.content)}
                </div>
              )}
            </div>
          ))}
        </main>
      </ClientLayout>
    </>
  )
}
export default Faqs
