import Head from 'next/head'
import ClientLayout from '../../shared/components/layout/client/Header'

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>Foody | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </Head>

      <ClientLayout>
        <div style={{ display: 'flex', justifyContent: 'space-around' }}>
          <div style={{ width: 500 }}>
            <h1
              style={{
                fontWeight: 'bold',
                fontSize: 30,
                position: 'relative',
                top: -20,
              }}
            >
              About Us
            </h1>
            <span className="font-sans leading-7">
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups. Lorem ipsum is placeholder text commonly used in the
              graphic, print, and publishing industries for previewing layouts
              and visual mockups.Lorem ipsum is placeholder text commonly used
              in the graphic, print, and publishing industries for previewing
              layouts and visual mockups.
            </span>
          </div>

          <div
            style={{
              background: '#FFB64F',
              width: 300,
              height: 450,
              borderRadius: 100,
              rotate: '30deg',
              position: 'relative',
            }}
          >
            <div
              style={{
                background: 'white',
                width: 150,
                height: 100,
                boxShadow: '10px 0 1000px rgba(0, 0, 0, 0.5)',
                position: 'absolute',
                left: 100,
                top: -10,
                rotate: '-15deg',
                borderRadius: 10,
              }}
            >
              <img
                src="hamburger.jpg"
                style={{
                  width: 70,
                  height: 70,
                  position: 'absolute',
                  left: 40,
                  top: -30,
                  background: 'white',
                  borderRadius: 200,
                }}
              />
              <span
                style={{ position: 'absolute', top: 40, fontWeight: 'bold' }}
              >
                Hamburger
              </span>
              <div
                style={{
                  width: 60,
                  display: 'flex',
                  justifyContent: 'space-around',
                  position: 'relative',
                  top: 65,
                }}
              >
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="rating.png" style={{ width: 7, height: 7 }} />
              </div>
              <span style={{ position: 'absolute', top: 75, left: 10 }}>
                $ 5.90
              </span>
            </div>

            <div
              style={{
                background: 'white',
                width: 150,
                height: 100,
                boxShadow: '10px 0 1000px rgba(0, 0, 0, 0.5)',
                position: 'absolute',
                left: -50,
                top: 200,
                rotate: '-15deg',
                borderRadius: 10,
              }}
            >
              <img
                src="mainPizza.svg"
                style={{
                  width: 70,
                  height: 70,
                  position: 'absolute',
                  left: 10,
                  top: -30,
                  background: 'white',
                  borderRadius: '100%',
                }}
              />
              <span
                style={{ position: 'absolute', top: 40, fontWeight: 'bold' }}
              >
                Sousage Pizza
              </span>
              <div
                style={{
                  width: 60,
                  display: 'flex',
                  justifyContent: 'space-around',
                  position: 'relative',
                  top: 65,
                }}
              >
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="rating.png" style={{ width: 7, height: 7 }} />
              </div>
              <span style={{ position: 'absolute', top: 75, left: 10 }}>
                $ 7.90
              </span>
            </div>

            <div
              style={{
                background: 'white',
                width: 150,
                height: 100,
                boxShadow: '10px 0 1000px rgba(0, 0, 0, 0.5)',
                position: 'absolute',
                right: -50,
                top: 200,
                rotate: '-15deg',
                borderRadius: 10,
              }}
            >
              <img
                src="tomatoSoup.jpg"
                style={{
                  width: 100,
                  height: 100,
                  position: 'absolute',
                  left: 40,
                  top: -30,
                  background: 'white',
                  borderRadius: 200,
                }}
              />
              <span
                style={{ position: 'absolute', top: 40, fontWeight: 'bold' }}
              >
                Tomato Soup
              </span>
              <div
                style={{
                  width: 60,
                  display: 'flex',
                  justifyContent: 'space-around',
                  position: 'relative',
                  top: 65,
                }}
              >
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="rating.png" style={{ width: 7, height: 7 }} />
              </div>
              <span style={{ position: 'absolute', top: 75, left: 10 }}>
                $ 7.90
              </span>
            </div>
            <div
              style={{
                background: 'white',
                width: 150,
                height: 100,
                boxShadow: '10px 0 1000px rgba(0, 0, 0, 0.5)',
                position: 'absolute',
                left: 100,
                bottom: -25,
                rotate: '-15deg',
                borderRadius: 10,
              }}
            >
              <img
                src="coffee.png"
                style={{
                  width: 80,
                  height: 80,
                  position: 'absolute',
                  left: 40,
                  top: -45,
                  background: 'white',
                  borderRadius: 200,
                }}
              />
              <span
                style={{ position: 'absolute', top: 40, fontWeight: 'bold' }}
              >
                Papa Coffee
              </span>
              <div
                style={{
                  width: 60,
                  display: 'flex',
                  justifyContent: 'space-around',
                  position: 'relative',
                  top: 65,
                }}
              >
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="star.png" style={{ width: 7, height: 7 }} />
                <img src="rating.png" style={{ width: 7, height: 7 }} />
              </div>
              <span style={{ position: 'absolute', top: 75, left: 10 }}>
                $ 1.40
              </span>
            </div>
          </div>
        </div>
      </ClientLayout>
    </>
  )
}
export default AboutUs
