import Head from 'next/head'
import ClientLayout from '../../shared/components/layout/client/Header'

const Error = () => {
  return (
    <>
      <Head>
        <title>Foody | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>

      <ClientLayout>
        <div>
          <img src={'/404.svg'} alt="404" style={{ width: '100%' }} />
        </div>
      </ClientLayout>
    </>
  )
}
export default Error
