import Head from 'next/head'
import ClientLayout from '../shared/components/layout/client/Header'

const Home = () => {
  return (
    <>
      <Head>
        <title>Foody | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>
      <ClientLayout />
    </>
  )
}
export default Home
