import Head from 'next/head'
import ClientLayout from '../../shared/components/layout/client/Header'

const HowItWorks = () => {
  return (
    <>
      <Head>
        <title>Foody | How It Works</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mainBurger.svg" />
      </Head>

      <ClientLayout>
        <div>howItWorks page</div>
      </ClientLayout>
    </>
  )
}
export default HowItWorks
